title: My Awesome Title
author: Gisselle
email: GIR170000@utdallas.edu
description: > I am editing and creating a description

# social links
twitter_username: doubleleaf
github_username:  GisselleIR

show_excerpts: true # set to false to remove excerpts on the homepage
